OnlineStore/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Data;
using OnlineStore.Models;

namespace OnlineStore.Controllers;

// Контроллер для работы с типами приложений.
[Authorize(Roles = WC.AdminRole)] // Доступ разрешен только для роли администратора.
public class ApplicationTypeController : Controller
{
    private readonly ApplicationDbContext _db;

    // Конструктор: инжекция зависимости для контекста базы данных.
    public ApplicationTypeController(ApplicationDbContext db)
    {
        _db = db;
    }

    // Метод для отображения списка типов приложений.
    public IActionResult Index()
    {
        IEnumerable<ApplicationType> objectList = _db.ApplicationTypes;
        return View(objectList);
    }

    // Метод для отображения страницы создания нового типа приложения.
    public IActionResult Create()
    {
        return View();
    }

    // Метод для обработки POST-запроса на создание нового типа приложения.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(ApplicationType type)
    {
        _db.ApplicationTypes.Add(type);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    // Метод для отображения страницы редактирования существующего типа приложения.
    public IActionResult Edit(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        //Find работает только с полем, имеющим атрибут первичный ключ!
        var model = _db.ApplicationTypes.Find(id);
        if (model == null)
        {
            return NotFound();
        }

        return View(model);
    }

    // Метод для обработки POST-запроса на редактирование типа приложения.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ApplicationType type)
    {
        if (ModelState.IsValid)
        {
            _db.ApplicationTypes.Update(type);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(type);
    }

    // Метод для отображения страницы удаления типа приложения.
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var type = _db.ApplicationTypes.Find(id);
        if (type == null)
        {
            return NotFound();
        }

        return View(type);
    }

    // Метод для обработки POST-запроса на удаление типа приложения.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var entity = _db.ApplicationTypes.Find(id);
        if (entity == null)
        {
            return NotFound();
        }

        _db.Remove(entity);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

OnlineStore/Views/ApplicationType/Create.cshtml
@model OnlineStore.Models.ApplicationType

<form method="post" asp-action="Create">
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Add Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                         <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fa-solid fa-right-from-bracket"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>

</form>
@section Scripts
{
    @{<partial name="_ValidationScriptsPartial"/>}
}

OnlineStore/Views/ApplicationType/Delete.cshtml
@model OnlineStore.Models.ApplicationType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">
                Delete Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control"/>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fa-solid fa-right-from-bracket"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>

</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

OnlineStore/Views/ApplicationType/Edit.cshtml
@model OnlineStore.Models.ApplicationType

<form method="post">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fa-solid fa-right-from-bracket"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>
    </div>

</form>
@section Scripts
{
    @{<partial name="_ValidationScriptsPartial"/>}
}

OnlineStore/Views/ApplicationType/Index.cshtml
@model IEnumerable<OnlineStore.Models.ApplicationType>

<div class="container p-3">
    <div class="row p-4">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> &nbsp;Create New Application Type
            </a>
        </div>
    </div>

    <br><br/>

    @if (Model.Any())
    {
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
            <tr>
                <th>Name</th>

                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">@obj.Name</td>
                    <td class="text-center">
                        <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                  
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <p>No application type exists.</p>
    }

</div>