OnlineStore/Controllers/CartController.cs
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Data;
using OnlineStore.Models;
using OnlineStore.Models.ViewModels;
using OnlineStore.Utility;

namespace OnlineStore.Controllers;

// Этот контроллер используется для работы с корзиной покупок
[Authorize] // Только авторизованные пользователи могут получить доступ
public class CartController : Controller
{
    private readonly ApplicationDbContext _db; // Ссылка на контекст базы данных
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IEmailSender _emailSender;
    [BindProperty] // Атрибут для автоматического связывания данных формы с этой моделью
    public ProductUserVM ProductUserVm { get; set; }

    // Конструктор для инициализации контекста базы данных
    public CartController(ApplicationDbContext dbContext, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender)
    {
        _db = dbContext;
        _webHostEnvironment = webHostEnvironment;
        _emailSender = emailSender;
    }

    // Метод для отображения содержимого корзины
    public IActionResult Index()
    {
        List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();

        // Проверка наличия товаров в корзине в сессии

        var shoppingCarts = HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart);
        if (shoppingCarts != null && shoppingCarts.Any())
        {
            shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }

        List<int> productInCart = shoppingCartList.Select(p => p.ProductId).ToList();
        IEnumerable<Product> products = _db.Product.Where(p => productInCart.Contains(p.Id));

        return View(products);
    }

    // POST-запрос для перехода к итоговой странице
    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Index")]
    public IActionResult IndexPost()
    {
        return RedirectToAction(nameof(Summary));
    }

    // Итоговая страница корзины с товарами - get
    public IActionResult Summary()
    {
        // Извлечение идентификатора текущего пользователя
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        //тоже самое
        //var userId = User.FindFirstValue(ClaimTypes.Value);

        List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Any())
        {
            shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }

        List<int> productInCart = shoppingCartList.Select(p => p.ProductId).ToList();
        IEnumerable<Product> products = _db.Product.Where(p => productInCart.Contains(p.Id));

        // Инициализация ViewModel
        ProductUserVm = new ProductUserVM()
        {
            ApplicationUser = _db.ApplicationUser.FirstOrDefault(u => u.Id == claim.Value),
            ProductList = products.ToList()
        };

        return View(ProductUserVm);
    }

    // Итоговая страница корзины с товарами - post
    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Summary")]
    public async Task<IActionResult> SummaryPost(ProductUserVM ProductUserVm)
    {
        var PathTotemplate = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString() +
                             "templates" + Path.DirectorySeparatorChar.ToString() + "Inquiry.html";

        var subject = "New Inquiry";
        string htmlBody = "";

        using (StreamReader streamReader = System.IO.File.OpenText(PathTotemplate))
        {
            htmlBody = streamReader.ReadToEnd();
        }
       //Name : {0}
       //Email  : {1}
       //Phone : {2}
       //Products: {3}

       StringBuilder productsListStringBuilder = new StringBuilder();

       foreach (var product in ProductUserVm.ProductList)
       {
           productsListStringBuilder.Append($" - Name{product.Name}<span style='font-size:14px;'>(- Id: {product.Id})</span><br />)");
       }

       string messageBody = string.Format(htmlBody,
           ProductUserVm.ApplicationUser.FullName,
           ProductUserVm.ApplicationUser.Email,
           ProductUserVm.ApplicationUser.PhoneNumber,
           productsListStringBuilder.ToString()
       );

       await _emailSender.SendEmailAsync(WC.EmailAdmin, subject, messageBody);
        return RedirectToAction(nameof(InquiryConfirmation));
    }

    public IActionResult InquiryConfirmation()
    {
        //очистить сессию
        HttpContext.Session.Clear();
        return View();
    }

    // Удаление товара из корзины
    public IActionResult Remove(int id)
    {
        List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Any())
        {
            shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }

        // Удаление выбранного товара
        shoppingCartList.Remove(shoppingCartList.FirstOrDefault(p => p.ProductId == id));

        // Обновление корзины в сессии
        HttpContext.Session.Set(WC.SessionCart, shoppingCartList);

        return RedirectToAction(nameof(Index));
    }
}

OnlineStore/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Data;
using OnlineStore.Models;

namespace OnlineStore.Controllers;
// Контроллер для работы с категориями продукции в интернет-магазине.
[Authorize(Roles = WC.AdminRole)] // Доступ к этому контроллеру разрешен только пользователям с ролью администратора
public class CategoryController : Controller
{
    private readonly ApplicationDbContext _db; // Ссылка на контекст базы данных для доступа к данным

    // Конструктор контроллера с зависимостью от контекста базы данных
    public CategoryController(ApplicationDbContext db)
    {
        _db = db;
    }

    // Отображение списка категорий
    public IActionResult Index()
    {
        IEnumerable<Category> objectList = _db.Category;
        return View(objectList);
    }

    // Отображение страницы создания новой категории
    public IActionResult Create()
    {
        return View();
    }

    // Обработка POST-запроса для создания новой категории
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category category)
    {
        if (ModelState.IsValid) // Проверка на валидность введенных данных
        {
            _db.Category.Add(category); // Добавление новой категории
            _db.SaveChanges(); // Сохранение изменений в базе данных
            return RedirectToAction("Index"); // Перенаправление на список категорий
        }

        return View(category); // Возвращение на страницу создания с введенными данными
    }

    // Отображение страницы редактирования категории
    public IActionResult Edit(int? id) // id категории передается как необязательный параметр
    {
        if (id == null || id == 0) // Проверка на валидность ID
        {
            return NotFound();
        }

        var category = _db.Category.Find(id); // Поиск категории по ID

        if (category == null) // Если категория не найдена
        {
            return NotFound();
        }

        return View(category);
    }

    // Обработка POST-запроса для редактирования категории
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category category)
    {
        if (ModelState.IsValid) // Проверка на валидность введенных данных
        {
            _db.Category.Update(category); // Обновление данных категории
            _db.SaveChanges(); // Сохранение изменений в базе данных
            return RedirectToAction("Index"); // Перенаправление на список категорий
        }

        return View(category); // Возвращение на страницу редактирования с введенными данными
    }

    // Отображение страницы удаления категории
    public IActionResult Delete(int? id) // id категории передается как необязательный параметр
    {
        if (id == null || id == 0) // Проверка на валидность ID
        {
            return NotFound();
        }

        var category = _db.Category.Find(id); // Поиск категории по ID

        if (category == null) // Если категория не найдена
        {
            return NotFound();
        }

        return View(category);
    }

    // Обработка POST-запроса для удаления категории
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var category = _db.Category.Find(id); // Поиск категории по ID
        if (category == null) // Если категория не найдена
        {
            return NotFound();
        }

        _db.Remove(category); // Удаление категории
        _db.SaveChanges(); // Сохранение изменений в базе данных
        return RedirectToAction("Index"); // Перенаправление на список категорий
    }
}

OnlineStore/Controllers/ProductController.cs
using System.ComponentModel.Design;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Data;
using OnlineStore.Models;
using OnlineStore.Models.ViewModels;

namespace OnlineStore.Controllers;
[Authorize(Roles = WC.AdminRole)]// Атрибут, который требует наличие роли "AdminRole" для доступа к методам этого контроллера.
public class ProductController : Controller
{
    // Зависимости: контекст базы данных и среда веб-хостинга
    private readonly ApplicationDbContext _db;
    private readonly IWebHostEnvironment _webHostEnvironment;

    // Конструктор контроллера, который принимает зависимости.
    public ProductController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
    {
        _db = db; // Инициализация контекста базы данных.
        _webHostEnvironment = webHostEnvironment; // Инициализация среды веб-хостинга.
    }

    // Метод для отображения всех продуктов.
    public IActionResult Index()
    {
        // Получение всех продуктов с их категориями и типами приложений.
        IEnumerable<Product> products = _db.Product.Include(p => p.Category).Include(p => p.ApplicationType);
        return View(products);
    }

    // Метод для добавления или редактирования продукта.
    public IActionResult Upsert(int? id)
    {
        // Создание представления модели с выпадающими списками категорий и типов приложений.
        ProductVM productVM = new ProductVM()
        {
            Product = new Product(),
            CategorySelectList = _db.Category.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString(),
            }),
            ApplicationTypeSelectList = _db.ApplicationTypes.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString(),
            })
        };

        // Если id равно null, это добавление нового продукта, иначе - редактирование существующего.
        if (id == null)
        {
            return View(productVM);
        }
        else
        {
            productVM.Product = _db.Product.Find(id);
            if (productVM.Product == null)
            {
                return NotFound();
            }
            return View(productVM);
        }
    }

    // Метод для добавления или редактирования продукта.
    //post-upsert
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM productVm)
    {
        // Проверка корректности данных.
        if (ModelState.IsValid)
        {
            var files = HttpContext.Request.Form.Files;
            string webRootPath = _webHostEnvironment.WebRootPath;

            if (productVm.Product.Id == 0)
            {
                //creating
                string fileName = Guid.NewGuid().ToString();
                productVm.Product.Image = CreateFile(webRootPath, fileName, files);
                _db.Product.Add(productVm.Product);
            }
            else
            {
                //updating
                var objectFromDb = _db.Product.AsNoTracking().FirstOrDefault(p => p.Id == productVm.Product.Id);
                productVm.Product.Image = files.Count > 0
                    ? CreateFile(webRootPath, objectFromDb.Image, files)
                    : objectFromDb.Image;
                _db.Product.Update(productVm.Product);
            }

            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        // Если данные не прошли проверку, то подготовка данных для повторного отображения формы.
        productVm.CategorySelectList = _db.Category.Select(i => new SelectListItem
        {
            Text = i.Name,
            Value = i.Id.ToString(),
        });
        productVm.ApplicationTypeSelectList = _db.ApplicationTypes.Select(i => new SelectListItem
        {
            Text = i.Name,
            Value = i.Id.ToString(),
        });

        if (!ModelState.IsValid)
        {
            foreach (var state in ModelState)
            {
                foreach (var error in state.Value.Errors)
                {
                    Console.WriteLine($"{state.Key} : {error.ErrorMessage}");
                }
            }
        }

        return View(productVm);
    }
// Метод для создания файла на сервере.
    private static string CreateFile(string webRootPath, string fileName, IFormFileCollection files)
    {
        // Определение пути для загрузки изображений.
        string upload = webRootPath + WC.ImagePath;
        // Получение расширения из первого файла в коллекции.
        string extension = Path.GetExtension(files[0].FileName);

        // Создание полного пути к старому файлу (если он существует).
        var oldFile = Path.Combine(upload, fileName);
        // Проверка существования файла и его удаление, если он существует.
        if (System.IO.File.Exists(oldFile))
        {
            System.IO.File.Delete(oldFile);
        }

        // Создание полного пути к новому файлу изображения.
        var productImagePath = fileName + extension;
        // Создание нового файла изображения на сервере.
        using (var fileStream = new FileStream(Path.Combine(upload, productImagePath), FileMode.Create))
        {
            files[0].CopyTo(fileStream);
        }

        // Возвращение пути к созданному файлу изображения.
        return productImagePath;
    }

    // Метод для отображения формы удаления продукта.
    //get-delete
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        // Получение продукта по id.
        var product = _db.Product.Include(p => p.Category).
            Include(p => p.ApplicationType).
            FirstOrDefault(p => p.Id == id);

        if (product == null)
        {
            return NotFound();
        }

        return View(product);
    }
    
    // Метод для выполнения удаления продукта.
    //post - delete
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var product = _db.Product.Find(id);
        if (product == null)
        {
            return NotFound();
        }

        // Удаление изображения продукта.
        string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;

        var oldFile = Path.Combine(upload, product.Image);

        if (System.IO.File.Exists(oldFile))
        {
            System.IO.File.Delete(oldFile);
        }

        // Удаление продукта из базы данных.
        _db.Product.Remove(product);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

OnlineStore/Views/Shared/_IndividualProductCard.cshtml
@model OnlineStore.Models.Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222; display: flex; flex-direction: column;"> <!-- Added flex styles -->
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label>@Model.Name</label></div>
            <div class="col-5 text-end"><span class="text-info h5">@String.Format("${0:N0}", Model.Price)</span></div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" style="max-height: 200px; object-fit: cover;" src="@WC.ImagePath/@Model.Image" alt="Card image cap"> <!-- Added styles here -->
        <div class="card-body p-1 px-3 row flex-grow-1"> <!-- Added flex-grow-1 -->
            <!-- ... (rest of your code) -->
        </div>
    


        
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush; color: black;">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100" style="background-color:aliceblue; color: black;">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify; color: black;">
                <p>@Model.ShortDescription</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

OnlineStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using OnlineStore.Utility
@inject IHttpContextAccessor HttpContextAccessor
@using OnlineStore.Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - OnlineStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/OnlineStore.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FontAwesome/css/all.css" asp-append-version="true"/>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStore</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item ">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.IsInRole(WC.AdminRole))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                            </ul>
                        </li>
                    }
                    <li>
                        @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                        {
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                }
                                <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                            </a>
                        }
                        else
                        {
                            <a href="#" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                            </a>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - OnlineStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>